Repository Sahil1786/Petari, pull requests merged in 2024-07, with the labels that each got.

#201 Create LICENSE
  LICENSE
Labels: documentation, GSSOC'2024, level1, gssoc

#197 UI updated (contact page)
  public/css/style.css
  public/img/1.png
  public/img/2.png
  public/img/3.png
  views/index.ejs
Labels: enhancement, GSSOC'2024, level2, gssoc

#208 Enhanced Readme
  README.md
Labels: documentation, GSSOC'2024, level1, gssoc

#181 added an AI-powered system to match food donors with recipients
  matching-model/.DS_Store
  matching-model/convertDStoCSV.py
  matching-model/main.py
Labels: GSSOC'2024, level2, gssoc
