Repository Sahil1786/Petari, pull requests merged in 2024-06, with the labels that each got.

#165 home page ui completed (#162)
  public/css/style.css
  public/img/mission.jpeg
  public/img/slider-2.jpg
  public/img/slider-7.jpg
  public/img/vision-2.jpg
  views/index.ejs
Labels: enhancement, GSSOC'2024, level3, gssoc

#163 Scroll to top
  views/index.ejs
  views/policies.ejs
Labels: good first issue, GSSOC'2024, level2, gssoc

#172 Implementing Food Donation Tracking in Petari
  model/user.js
  routers/NgoRoutes.js
  routers/userRoutes.js
  views/NGO-Dashboard.ejs
  views/UserDashBoard.ejs
Labels: enhancement, GSSOC'2024, level3, gssoc

#187 Added the animated hamburger/menu icon
  public/css/ngo_dashboard.css
  views/Admin_Dashboard.ejs
  views/NGO-Dashboard.ejs
  views/UserDashBoard.ejs
Labels: GSSOC'2024, level2, gssoc

#185 Automated Greeting Comments on Issue Closure
  .github/workflows/auto-comment-issue-close.yml
Labels: GSSOC'2024, level1, gssoc

#193 hover effect added on navbar
  public/css/style.css
Labels: GSSOC'2024, level1, gssoc
